### ISSUE TITLE
TcpEndpoint.kt:17-18: Create an object that converts...

### ISSUE THREAD

**Issue by 0pdd** [kerelape/reikai#6]
The puzzle `2-e252651a` from #2 has to be resolved: 

https://github.com/kerelape/reikai/blob/a4ea7f8cc2f9ec4cc99dd99ab225c96646a43735/src/main/kotlin/me/kerelape/reikai/io/network/TcpEndpoint.kt#L17-L18

The puzzle was created by Киряев Кирилл on 20-Jul-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
I can't create GITHUB labels `pdd`. Most likely I don't have necessary permissions to `kerelape/reikai` repository. Please, make sure @0pdd user is in the [list of collaborators](https://github.com/kerelape/reikai/settings/collaboration):

```Octokit::NotFound
POST https://api.github.com/repos/kerelape/reikai/labels: 404 - Not Found // See: https://docs.github.com/rest/reference/issues#create-a-label
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/response/raise_error.rb:14:in `on_complete'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/middleware.rb:18:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/response.rb:42:in `on_complete'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/connection.rb:281:in `post'
/app/vendor/bundle/ruby/2.7.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/connection.rb:28:in `post'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/client/labels.rb:44:in `add_label'
/app/objects/vcs/github.rb:78:in `add_label'
/app/objects/tickets/tagged_tickets.rb:45:in `block in submit'
/app/objects/tickets/tagged_tickets.rb:45:in `each'
/app/objects/tickets/tagged_tickets.rb:45:in `submit'
/app/objects/tickets/commit_tickets.rb:36:in `submit'
/app/objects/tickets/emailed_tickets.rb:35:in `submit'
/app/objects/tickets/sentry_tickets.rb:45:in `submit'
/app/objects/puzzles.rb:136:in `block in expose'
/app/objects/puzzles.rb:126:in `loop'
/app/objects/puzzles.rb:126:in `expose'
/app/objects/puzzles.rb:38:in `deploy'
/app/objects/jobs/job.rb:38:in `proceed'
/app/objects/jobs/job_starred.rb:32:in `proceed'
/app/objects/jobs/job_recorded.rb:31:in `proceed'
/app/objects/jobs/job_emailed.rb:33:in `proceed'
/app/objects/jobs/job_commiterrors.rb:33:in `proceed'
/app/objects/jobs/job_detached.rb:48:in `exclusive'
/app/objects/jobs/job_detached.rb:36:in `block in proceed'
/app/objects/jobs/job_detached.rb:36:in `fork'
/app/objects/jobs/job_detached.rb:36:in `proceed'
/app/0pdd.rb:517:in `process_request'
/app/0pdd.rb:355:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/logger.rb:17:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:255:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:248:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/handler/webrick.rb:95:in `service'
/app/vendor/ruby-2.7.6/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.7.6/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.7.6/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by Masynchin** [comment]
@kerelape can we do entity like this?

~~~kotlin
class IntegerAsText(i: Integer): Text(BigInteger(i.dataize()).toString())
~~~

Or it should accept Entity?

~~~kotlin
class IntegerAsText(e: Entity): Text(BigInteger(e.dataize()).toString())
~~~

**Comment by kerelape** [comment]
> @kerelape can we do entity like this?
> 
> ```kotlin
> class IntegerAsText(i: Integer): Text(BigInteger(i.dataize()).toString())
> ```
> 
> Or it should accept Entity?
> 
> ```kotlin
> class IntegerAsText(e: Entity): Text(BigInteger(e.dataize()).toString())
> ```

@Masynchin We must not use implementation iheretance, thus you cannot extend `Text`. Also `dataize` must ONLY be called from another suspend method. You can use `EntityWrap` for this. The name of the class is good, just make it like `class IntegerAsText(source: Entity) : EntityWrap(Entity { ... })`.

You can read this article to understand why you should use `EntityWrap`: https://www.yegor256.com/2017/01/31/decorating-envelopes.html

**Comment by kerelape** [comment]
@Masynchin I'll assign this issue to you, implement it, please

**Comment by Masynchin** [comment]
Thanks for explanation. I think that

> `dataize` must ONLY be called from another suspend method.

Should be referenced in README (#26) as core principe of Reikai.

**Comment by Masynchin** [comment]
I have struggled a bit with trying to implement `IntegerAsText` as decorator envelope, but here we are:


~~~kotlin
class IntegerAsText(source: Entity) : EntityWrap(Entity { Text(BigInteger(source.dataize()).toString()).dataize() })
~~~

I am asking for two way of improvement:

1) In terms of Kotlin. Is this correct way of using [functional interface](https://kotlinlang.org/docs/fun-interfaces.html)?
2) In terms of logic. Dataization happens two times, let me know if this amount can be reduced.

**Comment by kerelape** [comment]
> Thanks for explanation. I think that
> 
> > `dataize` must ONLY be called from another suspend method.
> 
> Should be referenced in README (#26) as core principe of Reikai.

Technically you cannot call `dataize` from a non-suspend function

**Comment by kerelape** [comment]
@Masynchin I think you may not understand the difference between *Initialization* and *Running*: in terms of Reikai, initialiation runs synchronously, while dataization (and any other work) runs asynchronously. These are conceptually different - this is why you may not (and cannot) dataize and object in a constructor (except using `runBlocking` of cource)

**Comment by kerelape** [comment]
> @Masynchin I think you may not understand the difference between _Initialization_ and _Running_: in terms of Reikai, initialiation runs synchronously, while dataization (and any other work) runs asynchronously. These are conceptually different - this is why you may not (and cannot) dataize and object in a constructor (except using `runBlocking` of cource)

I think I have to mention it in the README or create a manifest like for Q (https://gist.github.com/kerelape/78304e313adff2b1c63f381e111870b3)

**Comment by Masynchin** [comment]
> @Masynchin I think you may not understand the difference between _Initialization_ and _Running_: in terms of Reikai, initialiation runs synchronously, while dataization (and any other work) runs asynchronously. These are conceptually different - this is why you may not (and cannot) dataize and object in a constructor (except using `runBlocking` of cource)

Thanks for explanation again. I hope I won't need a third time 😁.
